sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
        event:
            routes:
                list: 'app.get_events'
                detail: 'app.get_event'
        event_type:
            routes:
                list: 'app.get_eventtypes'
                detail: 'app.get_eventtype'
        event_reoccurrence:
            routes:
                list: 'app.get_eventreoccurrences'
                detail: 'app.get_eventreoccurrence'
        web_user:
            routes:
                list: 'app.get_web_users'
                detail: 'app.get_web_user'
    field_type_options:
        selection:
            web_users_selection:
                default_type: 'list_overlay'
                resource_key: 'web_user'
                view:
                    name: 'app.web_user_edit_form'
                    result_to_view:
                        id: 'id'
                types:
                    list_overlay:
                        adapter: 'table'
                        list_key: 'web_user'
                        display_properties:
                            - 'id'
                            - 'firstName'
                            - 'lastName'
                            - 'email'
                        icon: 'su-user'
                        label: 'app.web_users'
                        overlay_title: 'app.web_users'
        single_selection:
            event_type_selection:
                default_type: 'list_overlay'
                resource_key: 'event_type'
                view:
                    name: 'app.event_type_edit_form'
                    result_to_view:
                        id: 'id'
                types:
                    list_overlay:
                        adapter: 'table'
                        list_key: 'event_type'
                        display_properties:
                            - 'id'
                            - 'name'
                        icon: 'su-tag'
                        overlay_title: 'app.event_type'
                        empty_text: 'app.location.no_selections'
