# Define your website routes here
controllers:
    resource: ../src/Controller/Website/
    type: attribute

app_event_web_api:
    path: /api/events/{month}
    controller: App\Controller\Website\EventController::getEventsForMonthAction
app_event_register_web_api:
    path: /api/event/register
    controller: App\Controller\Website\EventController::registerToEvent
app_event_users_count_web_api:
    path: /api/event/allocation/{eventId}
    controller: App\Controller\Website\EventController::getAllocationForEvent


logout:
    path: /logout
