# Define your admin routes here
controllers:
    resource: ../src/Controller/Admin/
    type: attribute

app_web_user_api:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\WebUserController
    name_prefix: app.

app_event_api:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\EventController
    name_prefix: app.

app_event_type_api:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\EventTypeController
    name_prefix: app.
